apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hy0f1uwzk-go 
  janus-idp.io/tekton: hy0f1uwzk-go
  backstage.io/kubernetes-id: hy0f1uwzk-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hy0f1uwzk-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml