apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hy0f1uwzk-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hy0f1uwzk-go 
  name: hy0f1uwzk-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hy0f1uwzk-go 
